name: venturi_dev

channels:
  - conda-forge
dependencies:
  - python>=3.13
  - pytorch-gpu>=2.9.1
  - torchvision>=0.24.1
  - lightning>=2.6.0
  - torchmetrics>=1.8.2
  - numpy>=2.3.5
  - pandas>=3.0.0
  - matplotlib>=3.10.8
  - wandb>=0.23.1
  - tqdm>=4.67.1
  - PyYAML>=6.0.3
  - optuna>=4.7.0
  - Pillow>=12.1.0
  - pip>=23.2.4
  - pytest>=8.0
  - pytest-cov>=5.0
  - pytest-mock>=3.15
  - mypy>=1.11
  - types-PyYAML
  - ruff>=0.4.0  
  - twine>=5.0
  - hatchling>=1.28.1
  - python-build>=1.4
  - pip:
    - install --no-build-isolation --no-deps -e .