name: venturi

channels:
  - conda-forge
dependencies:
  - python=3.13
  - pytorch-gpu>=2.9.1
  - torchvision>=0.24.1
  - lightning>=2.6.0
  - torchmetrics>=1.8.2
  - numpy>=2.3.5
  - pandas>=3.0.0
  - matplotlib>=3.10.8
  - wandb>=0.23.1
  - tqdm>=4.67.1
  - PyYAML>=6.0.3
  - optuna>=4.7.0
  - optuna-integration>=4.7.0
  - Pillow>=12.1.0
  - pip>=23.2.4