experiment_name: finetuning_experiment
seed: 42
model:
  _target_: Linear
  in_features: 128
  out_features: 2
  bias: true
optimizer:
  _target_: SGD
  lr: 0.01
  weight_decay: 0.0
  momentum: 0.9
data:
  batch_size: 32
  path: ./data/cats
