logging:
  create_folder: false
  log_csv: false
  log_plot: false
  log_training_time: false
  enable_progress_bar: false

dataset:
  setup:
    _target_: scripts.dataset.get_dataset
  num_classes: 10

model:
  setup:
    _target_: scripts.models.get_vit
  num_layers: 4
  hidden_dim: 32

losses:
  cross_entropy:
    instance:
      _target_: torch.nn.CrossEntropyLoss

metrics:
  setup:
    _target_: scripts.metrics.classification_metrics

training:
  trainer_params:
    max_epochs: 10
    check_val_every_n_epoch: 1
  validation_metric: "val/loss"
  maximize_validation_metric: false

optuna:
  study:
    storage: "sqlite:///my_experiment_db.sqlite3"
    study_name: "example"
    direction: "minimize"
    load_if_exists: true
    sampler:
      _target_: optuna.samplers.TPESampler
      multivariate: true
      warn_independent_sampling: false
      n_startup_trials: 10
      n_ei_candidates: 24
      seed: 0
    pruner:
      _target_: optuna.pruners.HyperbandPruner
      min_resource: 2
      max_resource: 10
      reduction_factor: 3

  study_optimize:
    n_trials: 100
    show_progress_bar: true

